services:
  api:
    build:
      context: .
      args:
        GIT_SHA: ${GIT_SHA:-dev}
    image: video-service-api:${GIT_SHA:-dev}
    container_name: video-service-api
    env_file: .env
    ports:
      - "8094:8094"
    depends_on:
      localstack:
        condition: service_healthy
    restart: unless-stopped

  localstack:
    image: localstack/localstack:stable
    container_name: localstack
    environment:
      - SERVICES=s3,sqs,dynamodb
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    healthcheck:
      test: ["CMD", "bash", "-lc", "awslocal s3 ls >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped
