version: "3.9"

services:
  api:
    build: .
    container_name: video-service-api
    env_file: .env
    ports: ["8094:8094"]
    depends_on:
      localstack:
        condition: service_healthy

  localstack:
    image: localstack/localstack:stable
    container_name: localstack
    environment:
      - SERVICES=s3,sqs,dynamodb
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      # <<< ADICIONE ESTA LINHA >>>
      - ./scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    healthcheck:
      # use algo que toque um serviço (s3 ls) para garantir readiness real
      test: ["CMD", "bash", "-lc", "awslocal s3 ls >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
